"""initial tables

Revision ID: 2b1e160e8df4
Revises: 
Create Date: 2026-07-28 21:38:28.026303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2b1e160e8df4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_assets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.Enum('user_raw', 'tts', 'assist', name='audio_kind'), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_assets_message_id'), 'audio_assets', ['message_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('human', 'ai', name='contact_type'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('tag', sa.String(length=32), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('emoji', sa.String(length=16), nullable=True),
    sa.Column('avatar_bg', sa.String(length=16), nullable=True),
    sa.Column('sub', sa.String(length=128), nullable=False),
    sa.Column('persona_prompt', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('avatar', sa.String(length=512), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('level_title', sa.String(length=64), nullable=False),
    sa.Column('total_hours', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=False),
    sa.Column('from_side', sa.Enum('them', 'me', name='msg_from'), nullable=False),
    sa.Column('en', sa.Text(), nullable=False),
    sa.Column('zh', sa.Text(), nullable=False),
    sa.Column('duration', sa.String(length=8), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('text_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_contact_id'), 'messages', ['contact_id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_contact_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('users')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_audio_assets_message_id'), table_name='audio_assets')
    op.drop_table('audio_assets')
    # ### end Alembic commands ###
